// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.3
// source: objectweaver.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Definition message
type Definition struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Type               string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                                                                       // Corresponds to Go's DataType field (as a string)
	Instruction        string                 `protobuf:"bytes,2,opt,name=instruction,proto3" json:"instruction,omitempty"`                                                                         // Corresponds to Go's Instruction field
	Properties         map[string]*Definition `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Corresponds to Go's Properties field
	Items              *Definition            `protobuf:"bytes,4,opt,name=items,proto3" json:"items,omitempty"`                                                                                     // Corresponds to Go's Items field
	Model              string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`                                                                                     // Corresponds to Go's ModelType field (as a string)
	ProcessingOrder    []string               `protobuf:"bytes,6,rep,name=processingOrder,proto3" json:"processingOrder,omitempty"`                                                                 // Corresponds to Go's ProcessingOrder field
	SystemPrompt       string                 `protobuf:"bytes,7,opt,name=systemPrompt,proto3" json:"systemPrompt,omitempty"`                                                                       // Corresponds to Go's SystemPrompt field
	Req                *RequestFormat         `protobuf:"bytes,8,opt,name=req,proto3" json:"req,omitempty"`                                                                                         // Corresponds to Go's Req field
	NarrowFocus        *Focus                 `protobuf:"bytes,9,opt,name=narrowFocus,proto3" json:"narrowFocus,omitempty"`                                                                         // Corresponds to Go's NarrowFocus field
	ImprovementProcess bool                   `protobuf:"varint,10,opt,name=improvementProcess,proto3" json:"improvementProcess,omitempty"`                                                         // Corresponds to Go's ImprovementProcess field
	SelectFields       []string               `protobuf:"bytes,11,rep,name=selectFields,proto3" json:"selectFields,omitempty"`                                                                      // Corresponds to Go's SelectFields field
	Choices            *Choices               `protobuf:"bytes,12,opt,name=choices,proto3" json:"choices,omitempty"`                                                                                // Corresponds to Go's Choices field
	Voters             bool                   `protobuf:"varint,13,opt,name=voters,proto3" json:"voters,omitempty"`                                                                                 // Corresponds to Go's Voters field
	HashMap            *HashMap               `protobuf:"bytes,14,opt,name=hashMap,proto3" json:"hashMap,omitempty"`                                                                                // Corresponds to Go's HashMap field
	TextToSpeech       *TextToSpeech          `protobuf:"bytes,15,opt,name=textToSpeech,proto3" json:"textToSpeech,omitempty"`                                                                      // Corresponds to Go's Audio field
	SpeechToText       *SpeechToText          `protobuf:"bytes,16,opt,name=speechToText,proto3" json:"speechToText,omitempty"`                                                                      // Corresponds to Go's Speech field
	Image              *Image                 `protobuf:"bytes,17,opt,name=image,proto3" json:"image,omitempty"`                                                                                    // Corresponds to Go's Image field
	SendImage          *SendImage             `protobuf:"bytes,18,opt,name=sendImage,proto3" json:"sendImage,omitempty"`                                                                            // Corresponds to Go's SendImage field
	Stream             bool                   `protobuf:"varint,19,opt,name=stream,proto3" json:"stream,omitempty"`
	Temp               float32                `protobuf:"fixed32,20,opt,name=temp,proto3" json:"temp,omitempty"`
	Priority           int32                  `protobuf:"varint,21,opt,name=priority,proto3" json:"priority,omitempty"`
	OverridePrompt     string                 `protobuf:"bytes,22,opt,name=overridePrompt,proto3" json:"overridePrompt,omitempty"`   // Corresponds to Go's OverridePrompt field
	DecisionPoint      *DecisionPoint         `protobuf:"bytes,23,opt,name=decisionPoint,proto3" json:"decisionPoint,omitempty"`     // Corresponds to Go's DecisionPoint field
	ScoringCriteria    *ScoringCriteria       `protobuf:"bytes,24,opt,name=scoringCriteria,proto3" json:"scoringCriteria,omitempty"` // Corresponds to Go's ScoringCriteria field
	RecursiveLoop      *RecursiveLoop         `protobuf:"bytes,25,opt,name=recursiveLoop,proto3" json:"recursiveLoop,omitempty"`     // Corresponds to Go's RecursiveLoop field
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Definition) Reset() {
	*x = Definition{}
	mi := &file_objectweaver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Definition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Definition) ProtoMessage() {}

func (x *Definition) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Definition.ProtoReflect.Descriptor instead.
func (*Definition) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{0}
}

func (x *Definition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Definition) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

func (x *Definition) GetProperties() map[string]*Definition {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Definition) GetItems() *Definition {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Definition) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Definition) GetProcessingOrder() []string {
	if x != nil {
		return x.ProcessingOrder
	}
	return nil
}

func (x *Definition) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *Definition) GetReq() *RequestFormat {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *Definition) GetNarrowFocus() *Focus {
	if x != nil {
		return x.NarrowFocus
	}
	return nil
}

func (x *Definition) GetImprovementProcess() bool {
	if x != nil {
		return x.ImprovementProcess
	}
	return false
}

func (x *Definition) GetSelectFields() []string {
	if x != nil {
		return x.SelectFields
	}
	return nil
}

func (x *Definition) GetChoices() *Choices {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *Definition) GetVoters() bool {
	if x != nil {
		return x.Voters
	}
	return false
}

func (x *Definition) GetHashMap() *HashMap {
	if x != nil {
		return x.HashMap
	}
	return nil
}

func (x *Definition) GetTextToSpeech() *TextToSpeech {
	if x != nil {
		return x.TextToSpeech
	}
	return nil
}

func (x *Definition) GetSpeechToText() *SpeechToText {
	if x != nil {
		return x.SpeechToText
	}
	return nil
}

func (x *Definition) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Definition) GetSendImage() *SendImage {
	if x != nil {
		return x.SendImage
	}
	return nil
}

func (x *Definition) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *Definition) GetTemp() float32 {
	if x != nil {
		return x.Temp
	}
	return 0
}

func (x *Definition) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Definition) GetOverridePrompt() string {
	if x != nil {
		return x.OverridePrompt
	}
	return ""
}

func (x *Definition) GetDecisionPoint() *DecisionPoint {
	if x != nil {
		return x.DecisionPoint
	}
	return nil
}

func (x *Definition) GetScoringCriteria() *ScoringCriteria {
	if x != nil {
		return x.ScoringCriteria
	}
	return nil
}

func (x *Definition) GetRecursiveLoop() *RecursiveLoop {
	if x != nil {
		return x.RecursiveLoop
	}
	return nil
}

// Audio message
type TextToSpeech struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`                 // Corresponds to Go's TextToSpeechModel field
	StringToAudio string                 `protobuf:"bytes,2,opt,name=stringToAudio,proto3" json:"stringToAudio,omitempty"` // Corresponds to Go's StringToAudio field
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`               // Corresponds to Go's Format field
	Voice         string                 `protobuf:"bytes,4,opt,name=voice,proto3" json:"voice,omitempty"`                 // Corresponds to Go's Voice field
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextToSpeech) Reset() {
	*x = TextToSpeech{}
	mi := &file_objectweaver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextToSpeech) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextToSpeech) ProtoMessage() {}

func (x *TextToSpeech) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextToSpeech.ProtoReflect.Descriptor instead.
func (*TextToSpeech) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{1}
}

func (x *TextToSpeech) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *TextToSpeech) GetStringToAudio() string {
	if x != nil {
		return x.StringToAudio
	}
	return ""
}

func (x *TextToSpeech) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *TextToSpeech) GetVoice() string {
	if x != nil {
		return x.Voice
	}
	return ""
}

// SpeechToText message
type SpeechToText struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Model             string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`                         // Corresponds to Go's SpeechToTextModel field
	AudioToTranscribe []byte                 `protobuf:"bytes,2,opt,name=audioToTranscribe,proto3" json:"audioToTranscribe,omitempty"` // Corresponds to Go's AudioToTranscribe field
	Language          string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`                   // Corresponds to Go's Language field
	Format            string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`                       // Corresponds to Go's Format field
	ToString          bool                   `protobuf:"varint,5,opt,name=toString,proto3" json:"toString,omitempty"`                  // Corresponds to Go's ToString field
	ToCaptions        bool                   `protobuf:"varint,6,opt,name=toCaptions,proto3" json:"toCaptions,omitempty"`              // Corresponds to Go's ToCaptions field
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SpeechToText) Reset() {
	*x = SpeechToText{}
	mi := &file_objectweaver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeechToText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeechToText) ProtoMessage() {}

func (x *SpeechToText) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeechToText.ProtoReflect.Descriptor instead.
func (*SpeechToText) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{2}
}

func (x *SpeechToText) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SpeechToText) GetAudioToTranscribe() []byte {
	if x != nil {
		return x.AudioToTranscribe
	}
	return nil
}

func (x *SpeechToText) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SpeechToText) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *SpeechToText) GetToString() bool {
	if x != nil {
		return x.ToString
	}
	return false
}

func (x *SpeechToText) GetToCaptions() bool {
	if x != nil {
		return x.ToCaptions
	}
	return false
}

// Image message
type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"` // Corresponds to Go's ImageModel field
	Size          string                 `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`   // Corresponds to Go's ImageSize field
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_objectweaver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{3}
}

func (x *Image) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Image) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

// Choices message
type Choices struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`  // Corresponds to Go's Number field
	Options       []string               `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"` // Corresponds to Go's Options field
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Choices) Reset() {
	*x = Choices{}
	mi := &file_objectweaver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Choices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Choices) ProtoMessage() {}

func (x *Choices) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Choices.ProtoReflect.Descriptor instead.
func (*Choices) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{4}
}

func (x *Choices) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Choices) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

// HashMap message
type HashMap struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	KeyInstruction  string                 `protobuf:"bytes,1,opt,name=keyInstruction,proto3" json:"keyInstruction,omitempty"`   // Corresponds to Go's KeyInstruction field
	FieldDefinition *Definition            `protobuf:"bytes,2,opt,name=fieldDefinition,proto3" json:"fieldDefinition,omitempty"` // Corresponds to Go's FieldDefinition field
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HashMap) Reset() {
	*x = HashMap{}
	mi := &file_objectweaver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashMap) ProtoMessage() {}

func (x *HashMap) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashMap.ProtoReflect.Descriptor instead.
func (*HashMap) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{5}
}

func (x *HashMap) GetKeyInstruction() string {
	if x != nil {
		return x.KeyInstruction
	}
	return ""
}

func (x *HashMap) GetFieldDefinition() *Definition {
	if x != nil {
		return x.FieldDefinition
	}
	return nil
}

// Focus message
type Focus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`              // Corresponds to Go's Prompt field
	Fields        []string               `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`              // Corresponds to Go's Fields field
	KeepOriginal  bool                   `protobuf:"varint,3,opt,name=keepOriginal,proto3" json:"keepOriginal,omitempty"` // Corresponds to Go's KeepOriginal field
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Focus) Reset() {
	*x = Focus{}
	mi := &file_objectweaver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Focus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Focus) ProtoMessage() {}

func (x *Focus) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Focus.ProtoReflect.Descriptor instead.
func (*Focus) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{6}
}

func (x *Focus) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Focus) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Focus) GetKeepOriginal() bool {
	if x != nil {
		return x.KeepOriginal
	}
	return false
}

// SendImage message
type SendImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImagesData    [][]byte               `protobuf:"bytes,1,rep,name=imagesData,proto3" json:"imagesData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendImage) Reset() {
	*x = SendImage{}
	mi := &file_objectweaver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendImage) ProtoMessage() {}

func (x *SendImage) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendImage.ProtoReflect.Descriptor instead.
func (*SendImage) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{7}
}

func (x *SendImage) GetImagesData() [][]byte {
	if x != nil {
		return x.ImagesData
	}
	return nil
}

// RequestFormat message
type RequestFormat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          *structpb.Struct       `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"` // This corresponds to Go's Body field as map[string]interface{}
	Authorization string                 `protobuf:"bytes,5,opt,name=authorization,proto3" json:"authorization,omitempty"`
	RequireFields []string               `protobuf:"bytes,6,rep,name=requireFields,proto3" json:"requireFields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestFormat) Reset() {
	*x = RequestFormat{}
	mi := &file_objectweaver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFormat) ProtoMessage() {}

func (x *RequestFormat) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFormat.ProtoReflect.Descriptor instead.
func (*RequestFormat) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{8}
}

func (x *RequestFormat) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RequestFormat) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestFormat) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *RequestFormat) GetBody() *structpb.Struct {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RequestFormat) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

func (x *RequestFormat) GetRequireFields() []string {
	if x != nil {
		return x.RequireFields
	}
	return nil
}

// DecisionPoint message
type DecisionPoint struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EvaluationPrompt string                 `protobuf:"bytes,2,opt,name=evaluationPrompt,proto3" json:"evaluationPrompt,omitempty"`
	Branches         []*ConditionalBranch   `protobuf:"bytes,3,rep,name=branches,proto3" json:"branches,omitempty"`
	Strategy         string                 `protobuf:"bytes,4,opt,name=strategy,proto3" json:"strategy,omitempty"` // RoutingStrategy as string
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DecisionPoint) Reset() {
	*x = DecisionPoint{}
	mi := &file_objectweaver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionPoint) ProtoMessage() {}

func (x *DecisionPoint) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionPoint.ProtoReflect.Descriptor instead.
func (*DecisionPoint) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{9}
}

func (x *DecisionPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DecisionPoint) GetEvaluationPrompt() string {
	if x != nil {
		return x.EvaluationPrompt
	}
	return ""
}

func (x *DecisionPoint) GetBranches() []*ConditionalBranch {
	if x != nil {
		return x.Branches
	}
	return nil
}

func (x *DecisionPoint) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

// ConditionalBranch message
type ConditionalBranch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Conditions    []*Condition           `protobuf:"bytes,2,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Logic         *Definition            `protobuf:"bytes,3,opt,name=logic,proto3" json:"logic,omitempty"`
	Then          *Definition            `protobuf:"bytes,4,opt,name=then,proto3" json:"then,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConditionalBranch) Reset() {
	*x = ConditionalBranch{}
	mi := &file_objectweaver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConditionalBranch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionalBranch) ProtoMessage() {}

func (x *ConditionalBranch) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionalBranch.ProtoReflect.Descriptor instead.
func (*ConditionalBranch) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{10}
}

func (x *ConditionalBranch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConditionalBranch) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *ConditionalBranch) GetLogic() *Definition {
	if x != nil {
		return x.Logic
	}
	return nil
}

func (x *ConditionalBranch) GetThen() *Definition {
	if x != nil {
		return x.Then
	}
	return nil
}

func (x *ConditionalBranch) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// Condition message
type Condition struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Field    string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Operator string                 `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"` // ComparisonOperator as string
	// Types that are valid to be assigned to Value:
	//
	//	*Condition_NumberValue
	//	*Condition_StringValue
	//	*Condition_BoolValue
	Value         isCondition_Value `protobuf_oneof:"value"`
	FieldPath     string            `protobuf:"bytes,6,opt,name=fieldPath,proto3" json:"fieldPath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_objectweaver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{11}
}

func (x *Condition) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Condition) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *Condition) GetValue() isCondition_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Condition) GetNumberValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*Condition_NumberValue); ok {
			return x.NumberValue
		}
	}
	return 0
}

func (x *Condition) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Condition_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Condition) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Condition_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Condition) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

type isCondition_Value interface {
	isCondition_Value()
}

type Condition_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,3,opt,name=number_value,json=numberValue,proto3,oneof"`
}

type Condition_StringValue struct {
	StringValue string `protobuf:"bytes,4,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Condition_BoolValue struct {
	BoolValue bool `protobuf:"varint,5,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*Condition_NumberValue) isCondition_Value() {}

func (*Condition_StringValue) isCondition_Value() {}

func (*Condition_BoolValue) isCondition_Value() {}

// ScoringCriteria message
type ScoringCriteria struct {
	state             protoimpl.MessageState       `protogen:"open.v1"`
	Dimensions        map[string]*ScoringDimension `protobuf:"bytes,1,rep,name=dimensions,proto3" json:"dimensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EvaluationModel   string                       `protobuf:"bytes,2,opt,name=evaluationModel,proto3" json:"evaluationModel,omitempty"`
	AggregationMethod string                       `protobuf:"bytes,3,opt,name=aggregationMethod,proto3" json:"aggregationMethod,omitempty"` // AggregationMethod as string
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ScoringCriteria) Reset() {
	*x = ScoringCriteria{}
	mi := &file_objectweaver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoringCriteria) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoringCriteria) ProtoMessage() {}

func (x *ScoringCriteria) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoringCriteria.ProtoReflect.Descriptor instead.
func (*ScoringCriteria) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{12}
}

func (x *ScoringCriteria) GetDimensions() map[string]*ScoringDimension {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *ScoringCriteria) GetEvaluationModel() string {
	if x != nil {
		return x.EvaluationModel
	}
	return ""
}

func (x *ScoringCriteria) GetAggregationMethod() string {
	if x != nil {
		return x.AggregationMethod
	}
	return ""
}

// ScoringDimension message
type ScoringDimension struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Scale         *ScoreScale            `protobuf:"bytes,2,opt,name=scale,proto3" json:"scale,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // ScoreType as string
	Weight        float64                `protobuf:"fixed64,4,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoringDimension) Reset() {
	*x = ScoringDimension{}
	mi := &file_objectweaver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoringDimension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoringDimension) ProtoMessage() {}

func (x *ScoringDimension) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoringDimension.ProtoReflect.Descriptor instead.
func (*ScoringDimension) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{13}
}

func (x *ScoringDimension) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ScoringDimension) GetScale() *ScoreScale {
	if x != nil {
		return x.Scale
	}
	return nil
}

func (x *ScoringDimension) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ScoringDimension) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

// ScoreScale message
type ScoreScale struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           int32                  `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           int32                  `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreScale) Reset() {
	*x = ScoreScale{}
	mi := &file_objectweaver_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreScale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreScale) ProtoMessage() {}

func (x *ScoreScale) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreScale.ProtoReflect.Descriptor instead.
func (*ScoreScale) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{14}
}

func (x *ScoreScale) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *ScoreScale) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

// RecursiveLoop message
type RecursiveLoop struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	MaxIterations           int32                  `protobuf:"varint,1,opt,name=maxIterations,proto3" json:"maxIterations,omitempty"`
	Selection               string                 `protobuf:"bytes,2,opt,name=selection,proto3" json:"selection,omitempty"` // SelectionStrategy as string
	TerminationPoint        *DecisionPoint         `protobuf:"bytes,3,opt,name=terminationPoint,proto3" json:"terminationPoint,omitempty"`
	FeedbackPrompt          string                 `protobuf:"bytes,4,opt,name=feedbackPrompt,proto3" json:"feedbackPrompt,omitempty"`
	IncludePreviousAttempts bool                   `protobuf:"varint,5,opt,name=includePreviousAttempts,proto3" json:"includePreviousAttempts,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RecursiveLoop) Reset() {
	*x = RecursiveLoop{}
	mi := &file_objectweaver_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecursiveLoop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecursiveLoop) ProtoMessage() {}

func (x *RecursiveLoop) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecursiveLoop.ProtoReflect.Descriptor instead.
func (*RecursiveLoop) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{15}
}

func (x *RecursiveLoop) GetMaxIterations() int32 {
	if x != nil {
		return x.MaxIterations
	}
	return 0
}

func (x *RecursiveLoop) GetSelection() string {
	if x != nil {
		return x.Selection
	}
	return ""
}

func (x *RecursiveLoop) GetTerminationPoint() *DecisionPoint {
	if x != nil {
		return x.TerminationPoint
	}
	return nil
}

func (x *RecursiveLoop) GetFeedbackPrompt() string {
	if x != nil {
		return x.FeedbackPrompt
	}
	return ""
}

func (x *RecursiveLoop) GetIncludePreviousAttempts() bool {
	if x != nil {
		return x.IncludePreviousAttempts
	}
	return false
}

// RequestBody message for the GenerateObject RPC
type RequestBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`         // Corresponds to Go's Prompt field
	Definition    *Definition            `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"` // Corresponds to Go's Definition field
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestBody) Reset() {
	*x = RequestBody{}
	mi := &file_objectweaver_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBody) ProtoMessage() {}

func (x *RequestBody) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBody.ProtoReflect.Descriptor instead.
func (*RequestBody) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{16}
}

func (x *RequestBody) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *RequestBody) GetDefinition() *Definition {
	if x != nil {
		return x.Definition
	}
	return nil
}

// Updated Response message for the GenerateObject RPC
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Struct       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // Use Struct to hold a dynamic map<string, any>
	UsdCost       float64                `protobuf:"fixed64,2,opt,name=usdCost,proto3" json:"usdCost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_objectweaver_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{17}
}

func (x *Response) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Response) GetUsdCost() float64 {
	if x != nil {
		return x.UsdCost
	}
	return 0
}

// StreamingResponse message for the stream method
type StreamingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Struct       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // Same as above, using Struct for map<string, any>
	UsdCost       float64                `protobuf:"fixed64,2,opt,name=usdCost,proto3" json:"usdCost,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // A status message for each streamed response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingResponse) Reset() {
	*x = StreamingResponse{}
	mi := &file_objectweaver_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingResponse) ProtoMessage() {}

func (x *StreamingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingResponse.ProtoReflect.Descriptor instead.
func (*StreamingResponse) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{18}
}

func (x *StreamingResponse) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamingResponse) GetUsdCost() float64 {
	if x != nil {
		return x.UsdCost
	}
	return 0
}

func (x *StreamingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_objectweaver_proto protoreflect.FileDescriptor

const file_objectweaver_proto_rawDesc = "" +
	"\n" +
	"\x12objectweaver.proto\x12\n" +
	"jsonSchema\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xb2\t\n" +
	"\n" +
	"Definition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12 \n" +
	"\vinstruction\x18\x02 \x01(\tR\vinstruction\x12F\n" +
	"\n" +
	"properties\x18\x03 \x03(\v2&.jsonSchema.Definition.PropertiesEntryR\n" +
	"properties\x12,\n" +
	"\x05items\x18\x04 \x01(\v2\x16.jsonSchema.DefinitionR\x05items\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12(\n" +
	"\x0fprocessingOrder\x18\x06 \x03(\tR\x0fprocessingOrder\x12\"\n" +
	"\fsystemPrompt\x18\a \x01(\tR\fsystemPrompt\x12+\n" +
	"\x03req\x18\b \x01(\v2\x19.jsonSchema.RequestFormatR\x03req\x123\n" +
	"\vnarrowFocus\x18\t \x01(\v2\x11.jsonSchema.FocusR\vnarrowFocus\x12.\n" +
	"\x12improvementProcess\x18\n" +
	" \x01(\bR\x12improvementProcess\x12\"\n" +
	"\fselectFields\x18\v \x03(\tR\fselectFields\x12-\n" +
	"\achoices\x18\f \x01(\v2\x13.jsonSchema.ChoicesR\achoices\x12\x16\n" +
	"\x06voters\x18\r \x01(\bR\x06voters\x12-\n" +
	"\ahashMap\x18\x0e \x01(\v2\x13.jsonSchema.HashMapR\ahashMap\x12<\n" +
	"\ftextToSpeech\x18\x0f \x01(\v2\x18.jsonSchema.TextToSpeechR\ftextToSpeech\x12<\n" +
	"\fspeechToText\x18\x10 \x01(\v2\x18.jsonSchema.SpeechToTextR\fspeechToText\x12'\n" +
	"\x05image\x18\x11 \x01(\v2\x11.jsonSchema.ImageR\x05image\x123\n" +
	"\tsendImage\x18\x12 \x01(\v2\x15.jsonSchema.SendImageR\tsendImage\x12\x16\n" +
	"\x06stream\x18\x13 \x01(\bR\x06stream\x12\x12\n" +
	"\x04temp\x18\x14 \x01(\x02R\x04temp\x12\x1a\n" +
	"\bpriority\x18\x15 \x01(\x05R\bpriority\x12&\n" +
	"\x0eoverridePrompt\x18\x16 \x01(\tR\x0eoverridePrompt\x12?\n" +
	"\rdecisionPoint\x18\x17 \x01(\v2\x19.jsonSchema.DecisionPointR\rdecisionPoint\x12E\n" +
	"\x0fscoringCriteria\x18\x18 \x01(\v2\x1b.jsonSchema.ScoringCriteriaR\x0fscoringCriteria\x12?\n" +
	"\rrecursiveLoop\x18\x19 \x01(\v2\x19.jsonSchema.RecursiveLoopR\rrecursiveLoop\x1aU\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.jsonSchema.DefinitionR\x05value:\x028\x01\"x\n" +
	"\fTextToSpeech\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12$\n" +
	"\rstringToAudio\x18\x02 \x01(\tR\rstringToAudio\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x14\n" +
	"\x05voice\x18\x04 \x01(\tR\x05voice\"\xc2\x01\n" +
	"\fSpeechToText\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12,\n" +
	"\x11audioToTranscribe\x18\x02 \x01(\fR\x11audioToTranscribe\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12\x1a\n" +
	"\btoString\x18\x05 \x01(\bR\btoString\x12\x1e\n" +
	"\n" +
	"toCaptions\x18\x06 \x01(\bR\n" +
	"toCaptions\"1\n" +
	"\x05Image\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x12\n" +
	"\x04size\x18\x02 \x01(\tR\x04size\";\n" +
	"\aChoices\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12\x18\n" +
	"\aoptions\x18\x02 \x03(\tR\aoptions\"s\n" +
	"\aHashMap\x12&\n" +
	"\x0ekeyInstruction\x18\x01 \x01(\tR\x0ekeyInstruction\x12@\n" +
	"\x0ffieldDefinition\x18\x02 \x01(\v2\x16.jsonSchema.DefinitionR\x0ffieldDefinition\"[\n" +
	"\x05Focus\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x16\n" +
	"\x06fields\x18\x02 \x03(\tR\x06fields\x12\"\n" +
	"\fkeepOriginal\x18\x03 \x01(\bR\fkeepOriginal\"+\n" +
	"\tSendImage\x12\x1e\n" +
	"\n" +
	"imagesData\x18\x01 \x03(\fR\n" +
	"imagesData\"\xb0\x02\n" +
	"\rRequestFormat\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12@\n" +
	"\aheaders\x18\x03 \x03(\v2&.jsonSchema.RequestFormat.HeadersEntryR\aheaders\x12+\n" +
	"\x04body\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04body\x12$\n" +
	"\rauthorization\x18\x05 \x01(\tR\rauthorization\x12$\n" +
	"\rrequireFields\x18\x06 \x03(\tR\rrequireFields\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x01\n" +
	"\rDecisionPoint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x10evaluationPrompt\x18\x02 \x01(\tR\x10evaluationPrompt\x129\n" +
	"\bbranches\x18\x03 \x03(\v2\x1d.jsonSchema.ConditionalBranchR\bbranches\x12\x1a\n" +
	"\bstrategy\x18\x04 \x01(\tR\bstrategy\"\xd4\x01\n" +
	"\x11ConditionalBranch\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\n" +
	"conditions\x18\x02 \x03(\v2\x15.jsonSchema.ConditionR\n" +
	"conditions\x12,\n" +
	"\x05logic\x18\x03 \x01(\v2\x16.jsonSchema.DefinitionR\x05logic\x12*\n" +
	"\x04then\x18\x04 \x01(\v2\x16.jsonSchema.DefinitionR\x04then\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\"\xcf\x01\n" +
	"\tCondition\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1a\n" +
	"\boperator\x18\x02 \x01(\tR\boperator\x12#\n" +
	"\fnumber_value\x18\x03 \x01(\x01H\x00R\vnumberValue\x12#\n" +
	"\fstring_value\x18\x04 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x05 \x01(\bH\x00R\tboolValue\x12\x1c\n" +
	"\tfieldPath\x18\x06 \x01(\tR\tfieldPathB\a\n" +
	"\x05value\"\x93\x02\n" +
	"\x0fScoringCriteria\x12K\n" +
	"\n" +
	"dimensions\x18\x01 \x03(\v2+.jsonSchema.ScoringCriteria.DimensionsEntryR\n" +
	"dimensions\x12(\n" +
	"\x0fevaluationModel\x18\x02 \x01(\tR\x0fevaluationModel\x12,\n" +
	"\x11aggregationMethod\x18\x03 \x01(\tR\x11aggregationMethod\x1a[\n" +
	"\x0fDimensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.jsonSchema.ScoringDimensionR\x05value:\x028\x01\"\x8e\x01\n" +
	"\x10ScoringDimension\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12,\n" +
	"\x05scale\x18\x02 \x01(\v2\x16.jsonSchema.ScoreScaleR\x05scale\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x01R\x06weight\"0\n" +
	"\n" +
	"ScoreScale\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x05R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max\"\xfc\x01\n" +
	"\rRecursiveLoop\x12$\n" +
	"\rmaxIterations\x18\x01 \x01(\x05R\rmaxIterations\x12\x1c\n" +
	"\tselection\x18\x02 \x01(\tR\tselection\x12E\n" +
	"\x10terminationPoint\x18\x03 \x01(\v2\x19.jsonSchema.DecisionPointR\x10terminationPoint\x12&\n" +
	"\x0efeedbackPrompt\x18\x04 \x01(\tR\x0efeedbackPrompt\x128\n" +
	"\x17includePreviousAttempts\x18\x05 \x01(\bR\x17includePreviousAttempts\"]\n" +
	"\vRequestBody\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x126\n" +
	"\n" +
	"definition\x18\x02 \x01(\v2\x16.jsonSchema.DefinitionR\n" +
	"definition\"Q\n" +
	"\bResponse\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x18\n" +
	"\ausdCost\x18\x02 \x01(\x01R\ausdCost\"r\n" +
	"\x11StreamingResponse\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x18\n" +
	"\ausdCost\x18\x02 \x01(\x01R\ausdCost\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status2\xa8\x01\n" +
	"\x11JSONSchemaService\x12?\n" +
	"\x0eGenerateObject\x12\x17.jsonSchema.RequestBody\x1a\x14.jsonSchema.Response\x12R\n" +
	"\x16StreamGeneratedObjects\x12\x17.jsonSchema.RequestBody\x1a\x1d.jsonSchema.StreamingResponse0\x01B\bZ\x06./grpcb\x06proto3"

var (
	file_objectweaver_proto_rawDescOnce sync.Once
	file_objectweaver_proto_rawDescData []byte
)

func file_objectweaver_proto_rawDescGZIP() []byte {
	file_objectweaver_proto_rawDescOnce.Do(func() {
		file_objectweaver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_objectweaver_proto_rawDesc), len(file_objectweaver_proto_rawDesc)))
	})
	return file_objectweaver_proto_rawDescData
}

var file_objectweaver_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_objectweaver_proto_goTypes = []any{
	(*Definition)(nil),        // 0: jsonSchema.Definition
	(*TextToSpeech)(nil),      // 1: jsonSchema.TextToSpeech
	(*SpeechToText)(nil),      // 2: jsonSchema.SpeechToText
	(*Image)(nil),             // 3: jsonSchema.Image
	(*Choices)(nil),           // 4: jsonSchema.Choices
	(*HashMap)(nil),           // 5: jsonSchema.HashMap
	(*Focus)(nil),             // 6: jsonSchema.Focus
	(*SendImage)(nil),         // 7: jsonSchema.SendImage
	(*RequestFormat)(nil),     // 8: jsonSchema.RequestFormat
	(*DecisionPoint)(nil),     // 9: jsonSchema.DecisionPoint
	(*ConditionalBranch)(nil), // 10: jsonSchema.ConditionalBranch
	(*Condition)(nil),         // 11: jsonSchema.Condition
	(*ScoringCriteria)(nil),   // 12: jsonSchema.ScoringCriteria
	(*ScoringDimension)(nil),  // 13: jsonSchema.ScoringDimension
	(*ScoreScale)(nil),        // 14: jsonSchema.ScoreScale
	(*RecursiveLoop)(nil),     // 15: jsonSchema.RecursiveLoop
	(*RequestBody)(nil),       // 16: jsonSchema.RequestBody
	(*Response)(nil),          // 17: jsonSchema.Response
	(*StreamingResponse)(nil), // 18: jsonSchema.StreamingResponse
	nil,                       // 19: jsonSchema.Definition.PropertiesEntry
	nil,                       // 20: jsonSchema.RequestFormat.HeadersEntry
	nil,                       // 21: jsonSchema.ScoringCriteria.DimensionsEntry
	(*structpb.Struct)(nil),   // 22: google.protobuf.Struct
}
var file_objectweaver_proto_depIdxs = []int32{
	19, // 0: jsonSchema.Definition.properties:type_name -> jsonSchema.Definition.PropertiesEntry
	0,  // 1: jsonSchema.Definition.items:type_name -> jsonSchema.Definition
	8,  // 2: jsonSchema.Definition.req:type_name -> jsonSchema.RequestFormat
	6,  // 3: jsonSchema.Definition.narrowFocus:type_name -> jsonSchema.Focus
	4,  // 4: jsonSchema.Definition.choices:type_name -> jsonSchema.Choices
	5,  // 5: jsonSchema.Definition.hashMap:type_name -> jsonSchema.HashMap
	1,  // 6: jsonSchema.Definition.textToSpeech:type_name -> jsonSchema.TextToSpeech
	2,  // 7: jsonSchema.Definition.speechToText:type_name -> jsonSchema.SpeechToText
	3,  // 8: jsonSchema.Definition.image:type_name -> jsonSchema.Image
	7,  // 9: jsonSchema.Definition.sendImage:type_name -> jsonSchema.SendImage
	9,  // 10: jsonSchema.Definition.decisionPoint:type_name -> jsonSchema.DecisionPoint
	12, // 11: jsonSchema.Definition.scoringCriteria:type_name -> jsonSchema.ScoringCriteria
	15, // 12: jsonSchema.Definition.recursiveLoop:type_name -> jsonSchema.RecursiveLoop
	0,  // 13: jsonSchema.HashMap.fieldDefinition:type_name -> jsonSchema.Definition
	20, // 14: jsonSchema.RequestFormat.headers:type_name -> jsonSchema.RequestFormat.HeadersEntry
	22, // 15: jsonSchema.RequestFormat.body:type_name -> google.protobuf.Struct
	10, // 16: jsonSchema.DecisionPoint.branches:type_name -> jsonSchema.ConditionalBranch
	11, // 17: jsonSchema.ConditionalBranch.conditions:type_name -> jsonSchema.Condition
	0,  // 18: jsonSchema.ConditionalBranch.logic:type_name -> jsonSchema.Definition
	0,  // 19: jsonSchema.ConditionalBranch.then:type_name -> jsonSchema.Definition
	21, // 20: jsonSchema.ScoringCriteria.dimensions:type_name -> jsonSchema.ScoringCriteria.DimensionsEntry
	14, // 21: jsonSchema.ScoringDimension.scale:type_name -> jsonSchema.ScoreScale
	9,  // 22: jsonSchema.RecursiveLoop.terminationPoint:type_name -> jsonSchema.DecisionPoint
	0,  // 23: jsonSchema.RequestBody.definition:type_name -> jsonSchema.Definition
	22, // 24: jsonSchema.Response.data:type_name -> google.protobuf.Struct
	22, // 25: jsonSchema.StreamingResponse.data:type_name -> google.protobuf.Struct
	0,  // 26: jsonSchema.Definition.PropertiesEntry.value:type_name -> jsonSchema.Definition
	13, // 27: jsonSchema.ScoringCriteria.DimensionsEntry.value:type_name -> jsonSchema.ScoringDimension
	16, // 28: jsonSchema.JSONSchemaService.GenerateObject:input_type -> jsonSchema.RequestBody
	16, // 29: jsonSchema.JSONSchemaService.StreamGeneratedObjects:input_type -> jsonSchema.RequestBody
	17, // 30: jsonSchema.JSONSchemaService.GenerateObject:output_type -> jsonSchema.Response
	18, // 31: jsonSchema.JSONSchemaService.StreamGeneratedObjects:output_type -> jsonSchema.StreamingResponse
	30, // [30:32] is the sub-list for method output_type
	28, // [28:30] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_objectweaver_proto_init() }
func file_objectweaver_proto_init() {
	if File_objectweaver_proto != nil {
		return
	}
	file_objectweaver_proto_msgTypes[11].OneofWrappers = []any{
		(*Condition_NumberValue)(nil),
		(*Condition_StringValue)(nil),
		(*Condition_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_objectweaver_proto_rawDesc), len(file_objectweaver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_objectweaver_proto_goTypes,
		DependencyIndexes: file_objectweaver_proto_depIdxs,
		MessageInfos:      file_objectweaver_proto_msgTypes,
	}.Build()
	File_objectweaver_proto = out.File
	file_objectweaver_proto_goTypes = nil
	file_objectweaver_proto_depIdxs = nil
}
