// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.3
// source: objectweaver.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Definition message
type Definition struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Type               string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                                                                       // Corresponds to Go's DataType field (as a string)
	Instruction        string                 `protobuf:"bytes,2,opt,name=instruction,proto3" json:"instruction,omitempty"`                                                                         // Corresponds to Go's Instruction field
	Properties         map[string]*Definition `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Corresponds to Go's Properties field
	Items              *Definition            `protobuf:"bytes,4,opt,name=items,proto3" json:"items,omitempty"`                                                                                     // Corresponds to Go's Items field
	Model              string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`                                                                                     // Corresponds to Go's ModelType field (as a string)
	ProcessingOrder    []string               `protobuf:"bytes,6,rep,name=processingOrder,proto3" json:"processingOrder,omitempty"`                                                                 // Corresponds to Go's ProcessingOrder field
	SystemPrompt       string                 `protobuf:"bytes,7,opt,name=systemPrompt,proto3" json:"systemPrompt,omitempty"`                                                                       // Corresponds to Go's SystemPrompt field
	Req                *RequestFormat         `protobuf:"bytes,8,opt,name=req,proto3" json:"req,omitempty"`                                                                                         // Corresponds to Go's Req field
	NarrowFocus        *Focus                 `protobuf:"bytes,9,opt,name=narrowFocus,proto3" json:"narrowFocus,omitempty"`                                                                         // Corresponds to Go's NarrowFocus field
	ImprovementProcess bool                   `protobuf:"varint,10,opt,name=improvementProcess,proto3" json:"improvementProcess,omitempty"`                                                         // Corresponds to Go's ImprovementProcess field
	SelectFields       []string               `protobuf:"bytes,11,rep,name=selectFields,proto3" json:"selectFields,omitempty"`                                                                      // Corresponds to Go's SelectFields field
	Choices            *Choices               `protobuf:"bytes,12,opt,name=choices,proto3" json:"choices,omitempty"`                                                                                // Corresponds to Go's Choices field
	Voters             bool                   `protobuf:"varint,13,opt,name=voters,proto3" json:"voters,omitempty"`                                                                                 // Corresponds to Go's Voters field
	HashMap            *HashMap               `protobuf:"bytes,14,opt,name=hashMap,proto3" json:"hashMap,omitempty"`                                                                                // Corresponds to Go's HashMap field
	TextToSpeech       *TextToSpeech          `protobuf:"bytes,15,opt,name=textToSpeech,proto3" json:"textToSpeech,omitempty"`                                                                      // Corresponds to Go's Audio field
	SpeechToText       *SpeechToText          `protobuf:"bytes,16,opt,name=speechToText,proto3" json:"speechToText,omitempty"`                                                                      // Corresponds to Go's Speech field
	Image              *Image                 `protobuf:"bytes,17,opt,name=image,proto3" json:"image,omitempty"`                                                                                    // Corresponds to Go's Image field
	SendImage          *SendImage             `protobuf:"bytes,18,opt,name=sendImage,proto3" json:"sendImage,omitempty"`                                                                            // Corresponds to Go's SendImage field
	Stream             bool                   `protobuf:"varint,19,opt,name=stream,proto3" json:"stream,omitempty"`
	Temp               float32                `protobuf:"fixed32,20,opt,name=temp,proto3" json:"temp,omitempty"`
	Priority           int32                  `protobuf:"varint,21,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Definition) Reset() {
	*x = Definition{}
	mi := &file_objectweaver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Definition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Definition) ProtoMessage() {}

func (x *Definition) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Definition.ProtoReflect.Descriptor instead.
func (*Definition) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{0}
}

func (x *Definition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Definition) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

func (x *Definition) GetProperties() map[string]*Definition {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Definition) GetItems() *Definition {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Definition) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Definition) GetProcessingOrder() []string {
	if x != nil {
		return x.ProcessingOrder
	}
	return nil
}

func (x *Definition) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *Definition) GetReq() *RequestFormat {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *Definition) GetNarrowFocus() *Focus {
	if x != nil {
		return x.NarrowFocus
	}
	return nil
}

func (x *Definition) GetImprovementProcess() bool {
	if x != nil {
		return x.ImprovementProcess
	}
	return false
}

func (x *Definition) GetSelectFields() []string {
	if x != nil {
		return x.SelectFields
	}
	return nil
}

func (x *Definition) GetChoices() *Choices {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *Definition) GetVoters() bool {
	if x != nil {
		return x.Voters
	}
	return false
}

func (x *Definition) GetHashMap() *HashMap {
	if x != nil {
		return x.HashMap
	}
	return nil
}

func (x *Definition) GetTextToSpeech() *TextToSpeech {
	if x != nil {
		return x.TextToSpeech
	}
	return nil
}

func (x *Definition) GetSpeechToText() *SpeechToText {
	if x != nil {
		return x.SpeechToText
	}
	return nil
}

func (x *Definition) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Definition) GetSendImage() *SendImage {
	if x != nil {
		return x.SendImage
	}
	return nil
}

func (x *Definition) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *Definition) GetTemp() float32 {
	if x != nil {
		return x.Temp
	}
	return 0
}

func (x *Definition) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

// Audio message
type TextToSpeech struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`                 // Corresponds to Go's TextToSpeechModel field
	StringToAudio string                 `protobuf:"bytes,2,opt,name=stringToAudio,proto3" json:"stringToAudio,omitempty"` // Corresponds to Go's StringToAudio field
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`               // Corresponds to Go's Format field
	Voice         string                 `protobuf:"bytes,4,opt,name=voice,proto3" json:"voice,omitempty"`                 // Corresponds to Go's Voice field
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextToSpeech) Reset() {
	*x = TextToSpeech{}
	mi := &file_objectweaver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextToSpeech) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextToSpeech) ProtoMessage() {}

func (x *TextToSpeech) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextToSpeech.ProtoReflect.Descriptor instead.
func (*TextToSpeech) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{1}
}

func (x *TextToSpeech) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *TextToSpeech) GetStringToAudio() string {
	if x != nil {
		return x.StringToAudio
	}
	return ""
}

func (x *TextToSpeech) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *TextToSpeech) GetVoice() string {
	if x != nil {
		return x.Voice
	}
	return ""
}

// SpeechToText message
type SpeechToText struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Model             string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`                         // Corresponds to Go's SpeechToTextModel field
	AudioToTranscribe []byte                 `protobuf:"bytes,2,opt,name=audioToTranscribe,proto3" json:"audioToTranscribe,omitempty"` // Corresponds to Go's AudioToTranscribe field
	Language          string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`                   // Corresponds to Go's Language field
	Format            string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`                       // Corresponds to Go's Format field
	ToString          bool                   `protobuf:"varint,5,opt,name=toString,proto3" json:"toString,omitempty"`                  // Corresponds to Go's ToString field
	ToCaptions        bool                   `protobuf:"varint,6,opt,name=toCaptions,proto3" json:"toCaptions,omitempty"`              // Corresponds to Go's ToCaptions field
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SpeechToText) Reset() {
	*x = SpeechToText{}
	mi := &file_objectweaver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeechToText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeechToText) ProtoMessage() {}

func (x *SpeechToText) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeechToText.ProtoReflect.Descriptor instead.
func (*SpeechToText) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{2}
}

func (x *SpeechToText) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SpeechToText) GetAudioToTranscribe() []byte {
	if x != nil {
		return x.AudioToTranscribe
	}
	return nil
}

func (x *SpeechToText) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SpeechToText) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *SpeechToText) GetToString() bool {
	if x != nil {
		return x.ToString
	}
	return false
}

func (x *SpeechToText) GetToCaptions() bool {
	if x != nil {
		return x.ToCaptions
	}
	return false
}

// Image message
type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"` // Corresponds to Go's ImageModel field
	Size          string                 `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`   // Corresponds to Go's ImageSize field
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_objectweaver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{3}
}

func (x *Image) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Image) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

// Choices message
type Choices struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`  // Corresponds to Go's Number field
	Options       []string               `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"` // Corresponds to Go's Options field
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Choices) Reset() {
	*x = Choices{}
	mi := &file_objectweaver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Choices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Choices) ProtoMessage() {}

func (x *Choices) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Choices.ProtoReflect.Descriptor instead.
func (*Choices) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{4}
}

func (x *Choices) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Choices) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

// HashMap message
type HashMap struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	KeyInstruction  string                 `protobuf:"bytes,1,opt,name=keyInstruction,proto3" json:"keyInstruction,omitempty"`   // Corresponds to Go's KeyInstruction field
	FieldDefinition *Definition            `protobuf:"bytes,2,opt,name=fieldDefinition,proto3" json:"fieldDefinition,omitempty"` // Corresponds to Go's FieldDefinition field
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HashMap) Reset() {
	*x = HashMap{}
	mi := &file_objectweaver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashMap) ProtoMessage() {}

func (x *HashMap) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashMap.ProtoReflect.Descriptor instead.
func (*HashMap) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{5}
}

func (x *HashMap) GetKeyInstruction() string {
	if x != nil {
		return x.KeyInstruction
	}
	return ""
}

func (x *HashMap) GetFieldDefinition() *Definition {
	if x != nil {
		return x.FieldDefinition
	}
	return nil
}

// Focus message
type Focus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`              // Corresponds to Go's Prompt field
	Fields        []string               `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`              // Corresponds to Go's Fields field
	KeepOriginal  bool                   `protobuf:"varint,3,opt,name=keepOriginal,proto3" json:"keepOriginal,omitempty"` // Corresponds to Go's KeepOriginal field
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Focus) Reset() {
	*x = Focus{}
	mi := &file_objectweaver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Focus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Focus) ProtoMessage() {}

func (x *Focus) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Focus.ProtoReflect.Descriptor instead.
func (*Focus) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{6}
}

func (x *Focus) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *Focus) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Focus) GetKeepOriginal() bool {
	if x != nil {
		return x.KeepOriginal
	}
	return false
}

// SendImage message
type SendImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImagesData    [][]byte               `protobuf:"bytes,1,rep,name=imagesData,proto3" json:"imagesData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendImage) Reset() {
	*x = SendImage{}
	mi := &file_objectweaver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendImage) ProtoMessage() {}

func (x *SendImage) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendImage.ProtoReflect.Descriptor instead.
func (*SendImage) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{7}
}

func (x *SendImage) GetImagesData() [][]byte {
	if x != nil {
		return x.ImagesData
	}
	return nil
}

// RequestFormat message
type RequestFormat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          *structpb.Struct       `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"` // This corresponds to Go's Body field as map[string]interface{}
	Authorization string                 `protobuf:"bytes,5,opt,name=authorization,proto3" json:"authorization,omitempty"`
	RequireFields []string               `protobuf:"bytes,6,rep,name=requireFields,proto3" json:"requireFields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestFormat) Reset() {
	*x = RequestFormat{}
	mi := &file_objectweaver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFormat) ProtoMessage() {}

func (x *RequestFormat) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFormat.ProtoReflect.Descriptor instead.
func (*RequestFormat) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{8}
}

func (x *RequestFormat) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RequestFormat) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestFormat) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *RequestFormat) GetBody() *structpb.Struct {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RequestFormat) GetAuthorization() string {
	if x != nil {
		return x.Authorization
	}
	return ""
}

func (x *RequestFormat) GetRequireFields() []string {
	if x != nil {
		return x.RequireFields
	}
	return nil
}

// RequestBody message for the GenerateObject RPC
type RequestBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`         // Corresponds to Go's Prompt field
	Definition    *Definition            `protobuf:"bytes,2,opt,name=definition,proto3" json:"definition,omitempty"` // Corresponds to Go's Definition field
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestBody) Reset() {
	*x = RequestBody{}
	mi := &file_objectweaver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBody) ProtoMessage() {}

func (x *RequestBody) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBody.ProtoReflect.Descriptor instead.
func (*RequestBody) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{9}
}

func (x *RequestBody) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *RequestBody) GetDefinition() *Definition {
	if x != nil {
		return x.Definition
	}
	return nil
}

// Updated Response message for the GenerateObject RPC
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Struct       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // Use Struct to hold a dynamic map<string, any>
	UsdCost       float64                `protobuf:"fixed64,2,opt,name=usdCost,proto3" json:"usdCost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_objectweaver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{10}
}

func (x *Response) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Response) GetUsdCost() float64 {
	if x != nil {
		return x.UsdCost
	}
	return 0
}

// StreamingResponse message for the stream method
type StreamingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Struct       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // Same as above, using Struct for map<string, any>
	UsdCost       float64                `protobuf:"fixed64,2,opt,name=usdCost,proto3" json:"usdCost,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // A status message for each streamed response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingResponse) Reset() {
	*x = StreamingResponse{}
	mi := &file_objectweaver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingResponse) ProtoMessage() {}

func (x *StreamingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_objectweaver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingResponse.ProtoReflect.Descriptor instead.
func (*StreamingResponse) Descriptor() ([]byte, []int) {
	return file_objectweaver_proto_rawDescGZIP(), []int{11}
}

func (x *StreamingResponse) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamingResponse) GetUsdCost() float64 {
	if x != nil {
		return x.UsdCost
	}
	return 0
}

func (x *StreamingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_objectweaver_proto protoreflect.FileDescriptor

const file_objectweaver_proto_rawDesc = "" +
	"\n" +
	"\x12objectweaver.proto\x12\n" +
	"jsonSchema\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc1\a\n" +
	"\n" +
	"Definition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12 \n" +
	"\vinstruction\x18\x02 \x01(\tR\vinstruction\x12F\n" +
	"\n" +
	"properties\x18\x03 \x03(\v2&.jsonSchema.Definition.PropertiesEntryR\n" +
	"properties\x12,\n" +
	"\x05items\x18\x04 \x01(\v2\x16.jsonSchema.DefinitionR\x05items\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12(\n" +
	"\x0fprocessingOrder\x18\x06 \x03(\tR\x0fprocessingOrder\x12\"\n" +
	"\fsystemPrompt\x18\a \x01(\tR\fsystemPrompt\x12+\n" +
	"\x03req\x18\b \x01(\v2\x19.jsonSchema.RequestFormatR\x03req\x123\n" +
	"\vnarrowFocus\x18\t \x01(\v2\x11.jsonSchema.FocusR\vnarrowFocus\x12.\n" +
	"\x12improvementProcess\x18\n" +
	" \x01(\bR\x12improvementProcess\x12\"\n" +
	"\fselectFields\x18\v \x03(\tR\fselectFields\x12-\n" +
	"\achoices\x18\f \x01(\v2\x13.jsonSchema.ChoicesR\achoices\x12\x16\n" +
	"\x06voters\x18\r \x01(\bR\x06voters\x12-\n" +
	"\ahashMap\x18\x0e \x01(\v2\x13.jsonSchema.HashMapR\ahashMap\x12<\n" +
	"\ftextToSpeech\x18\x0f \x01(\v2\x18.jsonSchema.TextToSpeechR\ftextToSpeech\x12<\n" +
	"\fspeechToText\x18\x10 \x01(\v2\x18.jsonSchema.SpeechToTextR\fspeechToText\x12'\n" +
	"\x05image\x18\x11 \x01(\v2\x11.jsonSchema.ImageR\x05image\x123\n" +
	"\tsendImage\x18\x12 \x01(\v2\x15.jsonSchema.SendImageR\tsendImage\x12\x16\n" +
	"\x06stream\x18\x13 \x01(\bR\x06stream\x12\x12\n" +
	"\x04temp\x18\x14 \x01(\x02R\x04temp\x12\x1a\n" +
	"\bpriority\x18\x15 \x01(\x05R\bpriority\x1aU\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.jsonSchema.DefinitionR\x05value:\x028\x01\"x\n" +
	"\fTextToSpeech\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12$\n" +
	"\rstringToAudio\x18\x02 \x01(\tR\rstringToAudio\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x14\n" +
	"\x05voice\x18\x04 \x01(\tR\x05voice\"\xc2\x01\n" +
	"\fSpeechToText\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12,\n" +
	"\x11audioToTranscribe\x18\x02 \x01(\fR\x11audioToTranscribe\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12\x1a\n" +
	"\btoString\x18\x05 \x01(\bR\btoString\x12\x1e\n" +
	"\n" +
	"toCaptions\x18\x06 \x01(\bR\n" +
	"toCaptions\"1\n" +
	"\x05Image\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x12\n" +
	"\x04size\x18\x02 \x01(\tR\x04size\";\n" +
	"\aChoices\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12\x18\n" +
	"\aoptions\x18\x02 \x03(\tR\aoptions\"s\n" +
	"\aHashMap\x12&\n" +
	"\x0ekeyInstruction\x18\x01 \x01(\tR\x0ekeyInstruction\x12@\n" +
	"\x0ffieldDefinition\x18\x02 \x01(\v2\x16.jsonSchema.DefinitionR\x0ffieldDefinition\"[\n" +
	"\x05Focus\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x16\n" +
	"\x06fields\x18\x02 \x03(\tR\x06fields\x12\"\n" +
	"\fkeepOriginal\x18\x03 \x01(\bR\fkeepOriginal\"+\n" +
	"\tSendImage\x12\x1e\n" +
	"\n" +
	"imagesData\x18\x01 \x03(\fR\n" +
	"imagesData\"\xb0\x02\n" +
	"\rRequestFormat\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12@\n" +
	"\aheaders\x18\x03 \x03(\v2&.jsonSchema.RequestFormat.HeadersEntryR\aheaders\x12+\n" +
	"\x04body\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04body\x12$\n" +
	"\rauthorization\x18\x05 \x01(\tR\rauthorization\x12$\n" +
	"\rrequireFields\x18\x06 \x03(\tR\rrequireFields\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\vRequestBody\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x126\n" +
	"\n" +
	"definition\x18\x02 \x01(\v2\x16.jsonSchema.DefinitionR\n" +
	"definition\"Q\n" +
	"\bResponse\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x18\n" +
	"\ausdCost\x18\x02 \x01(\x01R\ausdCost\"r\n" +
	"\x11StreamingResponse\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04data\x12\x18\n" +
	"\ausdCost\x18\x02 \x01(\x01R\ausdCost\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status2\xa8\x01\n" +
	"\x11JSONSchemaService\x12?\n" +
	"\x0eGenerateObject\x12\x17.jsonSchema.RequestBody\x1a\x14.jsonSchema.Response\x12R\n" +
	"\x16StreamGeneratedObjects\x12\x17.jsonSchema.RequestBody\x1a\x1d.jsonSchema.StreamingResponse0\x01B\bZ\x06./grpcb\x06proto3"

var (
	file_objectweaver_proto_rawDescOnce sync.Once
	file_objectweaver_proto_rawDescData []byte
)

func file_objectweaver_proto_rawDescGZIP() []byte {
	file_objectweaver_proto_rawDescOnce.Do(func() {
		file_objectweaver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_objectweaver_proto_rawDesc), len(file_objectweaver_proto_rawDesc)))
	})
	return file_objectweaver_proto_rawDescData
}

var file_objectweaver_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_objectweaver_proto_goTypes = []any{
	(*Definition)(nil),        // 0: jsonSchema.Definition
	(*TextToSpeech)(nil),      // 1: jsonSchema.TextToSpeech
	(*SpeechToText)(nil),      // 2: jsonSchema.SpeechToText
	(*Image)(nil),             // 3: jsonSchema.Image
	(*Choices)(nil),           // 4: jsonSchema.Choices
	(*HashMap)(nil),           // 5: jsonSchema.HashMap
	(*Focus)(nil),             // 6: jsonSchema.Focus
	(*SendImage)(nil),         // 7: jsonSchema.SendImage
	(*RequestFormat)(nil),     // 8: jsonSchema.RequestFormat
	(*RequestBody)(nil),       // 9: jsonSchema.RequestBody
	(*Response)(nil),          // 10: jsonSchema.Response
	(*StreamingResponse)(nil), // 11: jsonSchema.StreamingResponse
	nil,                       // 12: jsonSchema.Definition.PropertiesEntry
	nil,                       // 13: jsonSchema.RequestFormat.HeadersEntry
	(*structpb.Struct)(nil),   // 14: google.protobuf.Struct
}
var file_objectweaver_proto_depIdxs = []int32{
	12, // 0: jsonSchema.Definition.properties:type_name -> jsonSchema.Definition.PropertiesEntry
	0,  // 1: jsonSchema.Definition.items:type_name -> jsonSchema.Definition
	8,  // 2: jsonSchema.Definition.req:type_name -> jsonSchema.RequestFormat
	6,  // 3: jsonSchema.Definition.narrowFocus:type_name -> jsonSchema.Focus
	4,  // 4: jsonSchema.Definition.choices:type_name -> jsonSchema.Choices
	5,  // 5: jsonSchema.Definition.hashMap:type_name -> jsonSchema.HashMap
	1,  // 6: jsonSchema.Definition.textToSpeech:type_name -> jsonSchema.TextToSpeech
	2,  // 7: jsonSchema.Definition.speechToText:type_name -> jsonSchema.SpeechToText
	3,  // 8: jsonSchema.Definition.image:type_name -> jsonSchema.Image
	7,  // 9: jsonSchema.Definition.sendImage:type_name -> jsonSchema.SendImage
	0,  // 10: jsonSchema.HashMap.fieldDefinition:type_name -> jsonSchema.Definition
	13, // 11: jsonSchema.RequestFormat.headers:type_name -> jsonSchema.RequestFormat.HeadersEntry
	14, // 12: jsonSchema.RequestFormat.body:type_name -> google.protobuf.Struct
	0,  // 13: jsonSchema.RequestBody.definition:type_name -> jsonSchema.Definition
	14, // 14: jsonSchema.Response.data:type_name -> google.protobuf.Struct
	14, // 15: jsonSchema.StreamingResponse.data:type_name -> google.protobuf.Struct
	0,  // 16: jsonSchema.Definition.PropertiesEntry.value:type_name -> jsonSchema.Definition
	9,  // 17: jsonSchema.JSONSchemaService.GenerateObject:input_type -> jsonSchema.RequestBody
	9,  // 18: jsonSchema.JSONSchemaService.StreamGeneratedObjects:input_type -> jsonSchema.RequestBody
	10, // 19: jsonSchema.JSONSchemaService.GenerateObject:output_type -> jsonSchema.Response
	11, // 20: jsonSchema.JSONSchemaService.StreamGeneratedObjects:output_type -> jsonSchema.StreamingResponse
	19, // [19:21] is the sub-list for method output_type
	17, // [17:19] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_objectweaver_proto_init() }
func file_objectweaver_proto_init() {
	if File_objectweaver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_objectweaver_proto_rawDesc), len(file_objectweaver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_objectweaver_proto_goTypes,
		DependencyIndexes: file_objectweaver_proto_depIdxs,
		MessageInfos:      file_objectweaver_proto_msgTypes,
	}.Build()
	File_objectweaver_proto = out.File
	file_objectweaver_proto_goTypes = nil
	file_objectweaver_proto_depIdxs = nil
}
